// vue-demo/src/components/ui/Notifications.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Notifications
    </h4>

    <b-card no-body header="Alerts" header-tag="h6" class="mb-4">
      <div class="row no-gutters row-bordered">
        <div class="demo-vertical-spacing-sm col-sm-6 p-4">
          <div class="text-light small font-weight-semibold mb-3">Default</div>

          <b-alert show dismissible variant="primary">
            This is a primary alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="secondary">
            This is a secondary alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="success">
            This is a success alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="danger">
            This is a danger alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="warning">
            This is a warning alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="info">
            This is an info alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="dark">
            This is a dark alert — check it out!
          </b-alert>
        </div>

        <div class="demo-vertical-spacing-sm col-sm-6 p-4">
          <div class="text-light small font-weight-semibold mb-3">Dark</div>

          <b-alert show dismissible variant="dark-primary">
            This is a primary alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="dark-secondary">
            This is a secondary alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="dark-success">
            This is a success alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="dark-danger">
            This is a danger alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="dark-warning">
            This is a warning alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="dark-info">
            This is an info alert — check it out!
          </b-alert>

          <b-alert show dismissible variant="dark-dark">
            This is a dark alert — check it out!
          </b-alert>
        </div>
      </div>
    </b-card>

    <b-card no-body header="Bootstrap 4 toasts" header-tag="h6" class="mb-4">
      <div class="row no-gutters">
        <div class="col-md-6 p-4">
          <div class="text-light small font-weight-semibold mb-3">Default</div>

          <div class="bs4-toast toast show" :class="toast.variant" v-for="toast in bs4Toasts" :key="toast.title">
            <div class="toast-header">
              <img :src="publicUrl + toast.avatar" class="d-block ui-w-20 rounded mr-2" alt="">
              <div class="font-weight-bold mr-auto">{{ toast.title }}</div>
              <div class="d-block small">{{ toast.time }}</div>
              <button type="button" class="close d-block mb-1 ml-2" @click="closeBs4Toast(toast)">&times;</button>
            </div>
            <div class="toast-body">
              {{ toast.message }}
            </div>
          </div>

        </div>
        <div class="col-md-6 ui-bg-cover ui-bg-overlay-container p-4" :style="`background-image: url('${publicUrl}img/bg/1.jpg');`">
          <div class="ui-bg-overlay bg-dark opacity-50"></div>
          <div class="text-white small font-weight-semibold mb-3">Translucent</div>

          <div class="bs4-toast toast show" :class="toast.variant" v-for="toast in translucentBs4Toasts" :key="toast.title">
            <div class="toast-header">
              <img :src="publicUrl + toast.avatar" class="d-block ui-w-20 rounded mr-2" alt="">
              <div class="font-weight-bold mr-auto">{{ toast.title }}</div>
              <div class="d-block small">{{ toast.time }}</div>
              <button type="button" class="close d-block mb-1 ml-2" @click="closeTranslucentBs4Toast(toast)">&times;</button>
            </div>
            <div class="toast-body">
              {{ toast.message }}
            </div>
          </div>

        </div>
      </div>
    </b-card>

    <b-card header="Vue Notification" header-tag="h6" class="mb-4">
      <div class="cui-example-inline-spacing">
        <notifications group="notifications-default" />
        <notifications group="notifications-top-left" position="top left" />
        <notifications group="notifications-top-center" position="top center" />
        <notifications group="notifications-bottom-right" position="bottom right" />
        <notifications group="notifications-bottom-left" position="bottom left" />
        <notifications group="notifications-bottom-center" position="bottom center" />
        <notifications group="notifications-custom-template" :duration="5000" animation-name="v-fade-left" position="top left">
          <template slot="body" slot-scope="props">
            <div class="media bg-primary text-white p-3 mb-2" @click="props.close">
              <div class="media align-items-center w-100">
                <div class="mr-3">
                  <i class="pe-7s-shield" style="font-size: 250%;"></i>
                </div>
                <div class="media-body">
                  <strong>{{ props.item.title }}</strong><br>
                  {{ props.item.text }}
                </div>
              </div>
            </div>
          </template>
        </notifications>

        <!-- Examples -->
        <b-btn @click="showDefault('notifications-default')">Default</b-btn>
        <b-btn @click="showDefault('notifications-top-left')">Top Left</b-btn>
        <b-btn @click="showDefault('notifications-top-center')">Top Center</b-btn>
        <b-btn @click="showDefault('notifications-bottom-right')">Bottom Right</b-btn>
        <b-btn @click="showDefault('notifications-bottom-left')">Bottom Left</b-btn>
        <b-btn @click="showDefault('notifications-bottom-center')">Bottom Center</b-btn>

        <br>
        <br>

        <b-btn @click="showCustom('bg-secondary text-white')">Secondary</b-btn>
        <b-btn @click="showCustom('bg-success text-white')">Success</b-btn>
        <b-btn @click="showCustom('bg-warning text-body')">Warning</b-btn>
        <b-btn @click="showCustom('bg-info text-white')">Info</b-btn>
        <b-btn @click="showCustom('bg-danger text-white')">Danger</b-btn>
        <b-btn @click="showCustom('bg-dark text-white')">Dark</b-btn>

        <br>
        <br>

        <b-btn @click="showCustomTemplate()">Custom template</b-btn>
      </div>
    </b-card>

    <b-card header="Vue Toasted" header-tag="h6" class="mb-4">
      <label class="form-label mb-2">Text</label>
      <b-input v-model="toastText" />

      <label class="form-label mt-4 mb-2">Style</label>
      <b-radio-group v-model="toastStyle" :options="toastStyles" />

      <label class="form-label mt-4 mb-2">Vertical position</label>
      <b-radio-group v-model="toastVerticalPosition" :options="toastVerticalPositions" />

      <label class="form-label mt-4 mb-2">Horizontal position</label>
      <b-radio-group v-model="toastHorizontalPosition" :options="toastHorizontalPositions" />

      <label class="form-label mt-4 mb-2">Variant</label>
      <b-radio-group v-model="toastVariant" :options="toastVariants" />

      <div class="mt-4 mb-2">
        <b-check v-model="toastActions">Show actions</b-check>
      </div>

      <b-btn @click="showToast()" class="mt-4">Show Toast</b-btn>
    </b-card>

  </div>
</template>

<style src="@/vendor/libs/vue-notification/vue-notification.scss" lang="scss"></style>
<style src="@/vendor/libs/vue-toasted/vue-toasted.scss" lang="scss"></style>

<!-- Custom template animation -->
<style>
  .v-fade-left-enter-active,
  .v-fade-left-leave-active,
  .v-fade-left-move {
    transition: all .5s;
  }
  .v-fade-left-enter,
  .v-fade-left-leave-to {
    opacity: 0;
    transform: translateX(-500px) scale(0.2);
  }
</style>

<script>
import Vue from 'vue'
import Notifications from 'vue-notification'
import Toasted from 'vue-toasted'

Vue.use(Notifications)
Vue.use(Toasted)

export default {
  name: 'ui-notifications',
  metaInfo: {
    title: 'Notifications - UI elements'
  },
  data: () => ({
    //
    // Toasts
    //

    bs4Toasts: [{
      variant: null,
      avatar: 'img/avatars/1.png',
      title: 'Default',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-primary',
      avatar: 'img/avatars/1.png',
      title: 'Primary',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-secondary',
      avatar: 'img/avatars/1.png',
      title: 'Secondary',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-success',
      avatar: 'img/avatars/1.png',
      title: 'Success',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-warning',
      avatar: 'img/avatars/1.png',
      title: 'Warning',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-info',
      avatar: 'img/avatars/1.png',
      title: 'Info',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-danger',
      avatar: 'img/avatars/1.png',
      title: 'Danger',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-dark',
      avatar: 'img/avatars/1.png',
      title: 'Dark',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }],

    translucentBs4Toasts: [{
      variant: null,
      avatar: 'img/avatars/1.png',
      title: 'Default',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-primary',
      avatar: 'img/avatars/1.png',
      title: 'Primary',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-secondary',
      avatar: 'img/avatars/1.png',
      title: 'Secondary',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-success',
      avatar: 'img/avatars/1.png',
      title: 'Success',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-warning',
      avatar: 'img/avatars/1.png',
      title: 'Warning',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-info',
      avatar: 'img/avatars/1.png',
      title: 'Info',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-danger',
      avatar: 'img/avatars/1.png',
      title: 'Danger',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-dark',
      avatar: 'img/avatars/1.png',
      title: 'Dark',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }],

    //
    // vue-toasted
    //

    toastText: '<i class="ion ion-md-checkmark mr-2"></i> Toasted!',
    toastActions: false,

    toastStyle: 'toasted-primary',
    toastStyles: [
      { text: 'Default', value: 'toasted-primary' },
      { text: 'Bubble', value: 'bubble' },
      { text: 'Outline', value: 'outline' }
    ],

    toastVerticalPosition: 'top',
    toastVerticalPositions: [
      { text: 'Top', value: 'top' },
      { text: 'Bottom', value: 'bottom' }
    ],

    toastHorizontalPosition: 'right',
    toastHorizontalPositions: [
      { text: 'Left', value: 'left' },
      { text: 'Center', value: 'center' },
      { text: 'Right', value: 'right' }
    ],

    toastVariant: null,
    toastVariants: [
      { text: 'None', value: null },
      { text: 'Primary', value: 'primary' },
      { text: 'Secondary', value: 'secondary' },
      { text: 'Success', value: 'success' },
      { text: 'Warning', value: 'warning' },
      { text: 'Info', value: 'info' },
      { text: 'Danger', value: 'danger' },
      { text: 'Dark', value: 'dark' }
    ]
  }),
  methods: {
    //
    // Toasts
    //

    closeBs4Toast (toast) {
      const index = this.bs4Toasts.indexOf(toast)
      this.bs4Toasts.splice(index, 1)
    },

    closeTranslucentBs4Toast (toast) {
      const index = this.translucentBs4Toasts.indexOf(toast)
      this.translucentBs4Toasts.splice(index, 1)
    },

    //
    // vue-notification
    //

    showDefault (group) {
      this.$notify({
        group: group,
        title: 'Important message',
        text: 'Hello user! This is a notification!'
      })
    },
    showCustom (classes) {
      this.$notify({
        group: 'notifications-default',
        type: classes,
        title: 'Important message',
        text: 'Hello user! This is a notification!'
      })
    },
    showCustomTemplate () {
      this.$notify({
        group: 'notifications-custom-template',
        title: 'Important message',
        text: 'Hello user! This is a custom notification!'
      })
    },

    //
    // vue-toasted
    //

    getCustomClasses () {
      if (!this.toastVariant) return null

      if (this.toastStyle !== 'outline') {
        return `bg-${this.toastVariant} text-${this.toastVariant === 'warning' ? 'dark' : 'white'}`
      } else {
        return `border-${this.toastVariant} text-${this.toastVariant}`
      }
    },
    getActionCustomClasses () {
      if (!this.toastVariant) return null

      if (this.toastStyle !== 'outline') {
        return `opacity-75 text-${this.toastVariant === 'warning' ? 'dark' : 'white'}`
      } else {
        return `opacity-75 text-${this.toastVariant}`
      }
    },
    showToast () {
      const actions = [{
        text: 'Cancel',
        onClick: (e, toastObject) => {
          toastObject.goAway(0)
        },
        class: this.getActionCustomClasses()
      }, {
        text: 'Undo',
        push: {
          name: 'somewhere',
          dontClose: true
        },
        class: this.getActionCustomClasses()
      }]

      this.$toasted.show(this.toastText, {
        theme: this.toastStyle,
        position: `${this.toastVerticalPosition}-${this.toastHorizontalPosition}`,
        action: this.toastActions ? actions : null,
        icon: this.toastIcon || null,
        className: this.getCustomClasses(),
        duration: 4000
      })
    }
  }
}
</script>

// angular-demo/src/app/+ui/notifications/notifications.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { AppService } from '../../app.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'ui-notifications', // tslint:disable-line
  templateUrl: './notifications.component.html',
  styleUrls: ['../../../vendor/libs/ngx-toastr/ngx-toastr.scss'],
  encapsulation: ViewEncapsulation.None
})
export class NotificationsComponent {
  //
  // Alerts
  //

  public alerts: Array<IAlert> = [];
  public darkAlerts: Array<IAlert> = [];
  public bs4Toasts: any = [];
  public translucentBs4Toasts: any = [];

  //
  // ngx-toastr
  //

  title = '';
  message = '';
  type = 'success';
  tapToDismiss = true;
  closeButton = false;
  progressBar = false;
  preventDuplicates = false;
  newestOnTop = false;
  progressAnimation = 'decreasing';
  positionClass = 'toast-top-right';

  curMsgIndex = -1;

  constructor(private appService: AppService, public toastrService: ToastrService) {
    this.appService.pageTitle = 'Notifications - UI elements';

    //
    // Alerts
    //

    this.alerts.push({
      id: 1,
      type: 'primary',
      message: 'This is a primary alert — check it out!'
    }, {
      id: 2,
      type: 'secondary',
      message: 'This is a secondary alert — check it out!'
    }, {
      id: 3,
      type: 'success',
      message: 'This is a success alert — check it out!'
    }, {
      id: 4,
      type: 'danger',
      message: 'This is a danger alert — check it out!'
    }, {
      id: 5,
      type: 'warning',
      message: 'This is a warning alert — check it out!'
    }, {
      id: 6,
      type: 'info',
      message: 'This is an info alert — check it out!'
    }, {
      id: 7,
      type: 'dark',
      message: 'This is a dark alert — check it out!'
    });

    this.darkAlerts.push({
      id: 1,
      type: 'dark-primary',
      message: 'This is a primary alert — check it out!'
    }, {
      id: 2,
      type: 'dark-secondary',
      message: 'This is a secondary alert — check it out!'
    }, {
      id: 3,
      type: 'dark-success',
      message: 'This is a success alert — check it out!'
    }, {
      id: 4,
      type: 'dark-danger',
      message: 'This is a danger alert — check it out!'
    }, {
      id: 5,
      type: 'dark-warning',
      message: 'This is a warning alert — check it out!'
    }, {
      id: 6,
      type: 'dark-info',
      message: 'This is an info alert — check it out!'
    }, {
      id: 7,
      type: 'dark-dark',
      message: 'This is a dark alert — check it out!'
    });

    //
    // Toasts
    //

    this.bs4Toasts.push({
      variant: null,
      avatar: 'assets/img/avatars/1.png',
      title: 'Default',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-primary',
      avatar: 'assets/img/avatars/1.png',
      title: 'Primary',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-secondary',
      avatar: 'assets/img/avatars/1.png',
      title: 'Secondary',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-success',
      avatar: 'assets/img/avatars/1.png',
      title: 'Success',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-warning',
      avatar: 'assets/img/avatars/1.png',
      title: 'Warning',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-info',
      avatar: 'assets/img/avatars/1.png',
      title: 'Info',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-danger',
      avatar: 'assets/img/avatars/1.png',
      title: 'Danger',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-dark',
      avatar: 'assets/img/avatars/1.png',
      title: 'Dark',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    });

    this.translucentBs4Toasts.push({
      variant: null,
      avatar: 'assets/img/avatars/1.png',
      title: 'Default',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-primary',
      avatar: 'assets/img/avatars/1.png',
      title: 'Primary',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-secondary',
      avatar: 'assets/img/avatars/1.png',
      title: 'Secondary',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-success',
      avatar: 'assets/img/avatars/1.png',
      title: 'Success',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-warning',
      avatar: 'assets/img/avatars/1.png',
      title: 'Warning',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-info',
      avatar: 'assets/img/avatars/1.png',
      title: 'Info',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-danger',
      avatar: 'assets/img/avatars/1.png',
      title: 'Danger',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    }, {
      variant: 'bg-dark',
      avatar: 'assets/img/avatars/1.png',
      title: 'Dark',
      time: '11 mins ago',
      message: 'Hello, world! This is a toast message.'
    });

  }

  //
  // Alerts
  //

  public closeAlert(alert: IAlert) {
    const index: number = this.alerts.indexOf(alert);
    this.alerts.splice(index, 1);
  }

  public closeDarkAlert(darkAlert: IAlert) {
    const index: number = this.darkAlerts.indexOf(darkAlert);
    this.darkAlerts.splice(index, 1);
  }

  //
  // Toasts
  //

  public closeBs4Toast(toast: any) {
    const index: number = this.bs4Toasts.indexOf(toast);
    this.bs4Toasts.splice(index, 1);
  }

  public closeTranslucentBs4Toast(toast: any) {
    const index: number = this.translucentBs4Toasts.indexOf(toast);
    this.translucentBs4Toasts.splice(index, 1);
  }

  //
  // ngx-toastr
  //

  getMessage() {
    const msgs = [
      'My name is Inigo Montoya. You killed my father. Prepare to die!',
      'Are you the six fingered man?',
      'Inconceivable!',
      'I do not think that means what you think it means.',
      'Have fun storming the castle!',
    ];

    this.curMsgIndex++;

    if (this.curMsgIndex === msgs.length) { this.curMsgIndex = 0; }

    return msgs[this.curMsgIndex];
  }

  showToast() {
    const options = {
      tapToDismiss: this.tapToDismiss,
      closeButton: this.closeButton,
      progressBar: this.progressBar,
      progressAnimation: this.progressAnimation,
      positionClass: this.positionClass,
      rtl: this.appService.isRTL
    };

    // `newestOnTop` and `preventDuplicates` options must be set on global config
    this.toastrService.toastrConfig.newestOnTop = this.newestOnTop;
    this.toastrService.toastrConfig.preventDuplicates = this.preventDuplicates;

    this.toastrService[this.type](this.message || this.getMessage(), this.title, options);
  }

  clearToasts() {
    this.toastrService.clear();
  }
}

export interface IAlert {
  id: number;
  type: string;
  message: string;
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Notifications
</h4>

<div class="card mb-4">
  <h6 class="card-header">
    Alerts
  </h6>
  <div class="row no-gutters row-bordered">
    <div class="demo-vertical-spacing-sm col-sm-6 p-4">
      <div class="text-light small font-weight-semibold mb-3">Default</div>

      <p *ngFor="let alert of alerts">
        <ngb-alert [type]="alert.type" (close)="closeAlert(alert)">{{ alert.message }}</ngb-alert>
      </p>
    </div>

    <div class="demo-vertical-spacing-sm col-sm-6 p-4">
      <div class="text-light small font-weight-semibold mb-3">Dark</div>

      <p *ngFor="let alert of darkAlerts">
        <ngb-alert [type]="alert.type" (close)="closeDarkAlert(alert)">{{ alert.message }}</ngb-alert>
      </p>
    </div>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    Bootstrap 4 toasts
  </h6>
  <div class="row no-gutters">
    <div class="col-md-6 p-4">
      <div class="text-light small font-weight-semibold mb-3">Default</div>

      <div class="bs4-toast toast show" [ngClass]="toast.variant" *ngFor="let toast of bs4Toasts">
        <div class="toast-header">
          <img [src]="toast.avatar" class="d-block ui-w-20 rounded mr-2" alt="">
          <div class="font-weight-bold mr-auto">{{ toast.title }}</div>
          <div class="d-block small">{{ toast.time }}</div>
          <button type="button" class="close d-block mb-1 ml-2" (click)="closeBs4Toast(toast)">&times;</button>
        </div>
        <div class="toast-body">
          {{ toast.message }}
        </div>
      </div>

    </div>
    <div class="col-md-6 ui-bg-cover ui-bg-overlay-container p-4" style="background-image: url('assets/img/bg/1.jpg');">
      <div class="ui-bg-overlay bg-dark opacity-50"></div>
      <div class="text-white small font-weight-semibold mb-3">Translucent</div>

      <div class="bs4-toast toast show" [ngClass]="toast.variant" *ngFor="let toast of translucentBs4Toasts">
        <div class="toast-header">
          <img [src]="toast.avatar" class="d-block ui-w-20 rounded mr-2" alt="">
          <div class="font-weight-bold mr-auto">{{ toast.title }}</div>
          <div class="d-block small">{{ toast.time }}</div>
          <button type="button" class="close d-block mb-1 ml-2" (click)="closeTranslucentBs4Toast(toast)">&times;</button>
        </div>
        <div class="toast-body">
          {{ toast.message }}
        </div>
      </div>

    </div>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    ngx-toastr
  </h6>
  <div class="card-body">
    <div class="row">
      <div class="col-xs-12 col-md-7">
        <div class="form-group">
          <label class="form-label">Title</label>
          <input [(ngModel)]="title" type="text" class="form-control" placeholder="Enter a title...">
        </div>
        <div class="form-group">
          <label class="form-label">Message</label>
          <input [(ngModel)]="message" type="text" class="form-control" placeholder="Enter a message...">
        </div>
        <div class="form-group">
          <label class="form-label">Type</label>
          <select [(ngModel)]="type" class="custom-select form-control">
            <option value="success">Success</option>
            <option value="info">Info</option>
            <option value="warning">Warning</option>
            <option value="error">Error</option>
          </select>
        </div>
        <div class="form-group custom-controls-stacked">
          <label class="custom-control custom-checkbox">
            <input [(ngModel)]="tapToDismiss" type="checkbox" class="custom-control-input">
            <span class="custom-control-label">Tap to dismiss</span>
          </label>
          <label class="custom-control custom-checkbox">
            <input [(ngModel)]="closeButton" type="checkbox" class="custom-control-input">
            <span class="custom-control-label">Close button</span>
          </label>
          <label class="custom-control custom-checkbox">
            <input [(ngModel)]="progressBar" type="checkbox" class="custom-control-input">
            <span class="custom-control-label">Progress bar</span>
          </label>
          <label class="custom-control custom-checkbox">
            <input [(ngModel)]="preventDuplicates" type="checkbox" class="custom-control-input">
            <span class="custom-control-label">Prevent duplicates</span>
          </label>
          <label class="custom-control custom-checkbox">
            <input [(ngModel)]="newestOnTop" type="checkbox" class="custom-control-input">
            <span class="custom-control-label">Newest on top</span>
          </label>
        </div>
      </div>
      <div class="col-xs-12 col-md-5">
        <div class="form-group custom-controls-stacked">
          <label class="form-label mb-2">Progress bar animation</label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="progressAnimation" [disabled]="!progressBar" value="decreasing" name="toastr-progress-bar-animation" type="radio" class="custom-control-input">
            <span class="custom-control-label">Decreasing</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="progressAnimation" [disabled]="!progressBar" value="increasing" name="toastr-progress-bar-animation" type="radio" class="custom-control-input">
            <span class="custom-control-label">Increasing</span>
          </label>
        </div>

        <div class="form-group custom-controls-stacked">
          <label class="form-label mb-2">Position</label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-top-right" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Top Right</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-bottom-right" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Bottom Right</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-bottom-left" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Bottom Left</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-top-left" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Top Left</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-top-full-width" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Top Full Width</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-bottom-full-width" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Bottom Full Width</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-top-center" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Top Center</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-bottom-center" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Bottom Center</span>
          </label>
          <label class="custom-control custom-radio">
            <input [(ngModel)]="positionClass" value="toast-center-center" name="toastr-position" type="radio" class="custom-control-input">
            <span class="custom-control-label">Center Center</span>
          </label>
        </div>
      </div>
    </div>

    <hr>

    <button class="btn btn-primary mr-1" (click)="showToast()">Show toast</button>
    <button class="btn btn-default mr-1" (click)="clearToasts()">Clear toasts</button>
  </div>
</div>
