// angular-demo/src/app/+forms/sliders/sliders.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'forms-sliders', // tslint:disable-line
  templateUrl: './sliders.component.html',
  styleUrls: [
    '../../../vendor/libs/ng2-nouislider/ng2-nouislider.scss',
    './sliders.scss'
  ]
})
export class SlidersComponent {

  // Bootstrap 4 slider

  bs4SliderValue = 35;

  // Single value slider

  singleValue1: number[] = [80];
  singleValue2: number[] = [80];
  singleConfig = {
    direction: 'ltr'
  };
  verticalSingleConfig = {
    orientation: 'vertical',
    direction: 'rtl'
  };

  // Range slider

  rangeValue1 = [ 2050, 3000 ];
  rangeValue2 = [ 2050, 3000 ];
  rangeValue3 = [ 2050, 3000 ];
  rangeValue4 = [ 2050, 3000 ];
  rangeValue5 = [ 2050, 3000 ];
  rangeValue6 = [ 2050, 3000 ];
  rangeValue7 = [ 2050, 3000 ];
  rangeValue8 = [ 2050, 3000 ];
  rangeConfig = {
    connect: true,
    step: 150,
    range: {
      'min': 1000,
      'max': 3750
    },
    direction: 'ltr'
  };

  // Full example

  fullValue1 = [ 1450, 2050, 2350, 3000 ];
  fullValue2 = [ 1450, 2050, 2350, 3000 ];
  fullConfig = {
    connect: true,
    behaviour: 'tap-drag',
    step: 150,
    tooltips: true,
    range: {
      'min': 1000,
      'max': 3750
    },
    pips: {
      mode: 'steps',
      stepped: true,
      density: 4
    },
    direction: 'ltr'
  };
  verticalFullConfig = {
    connect: true,
    behaviour: 'tap-drag',
    step: 150,
    tooltips: true,
    orientation: 'vertical',
    range: {
      'min': 1000,
      'max': 3750
    },
    pips: {
      mode: 'steps',
      stepped: true,
      density: 4
    },
    direction: 'rtl'
  };

  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Sliders - Forms';

    if (appService.isRTL) {
      this.singleConfig.direction = 'rtl';
      this.rangeConfig.direction = 'rtl';
      this.fullConfig.direction = 'rtl';
    }
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Forms /</span> Sliders
</h4>

<div class="card mb-4">
  <h6 class="card-header">
    Default Bootstrap 4 slider
  </h6>
  <div class="card-body demo-vertical-spacing">
    <input type="range" [(ngModel)]="bs4SliderValue" class="custom-range">
    <p>Value: <strong>{{ bs4SliderValue }}</strong></p>

    <input type="range" [(ngModel)]="bs4SliderValue" class="custom-range" disabled>
  </div>
</div>

<div class="card mb-4">
  <h6 class="card-header">
    ng2-nouislider
  </h6>
  <div class="card-body demo-vertical-spacing-lg p-5 mb-4">
    <nouislider
      [connect]="[true, false]"
      [min]="0"
      [max]="100"
      [config]="singleConfig"
      [(ngModel)]="singleValue1">
    </nouislider>

    <nouislider
      [connect]="[true, false]"
      [min]="0"
      [max]="100"
      [config]="verticalSingleConfig"
      [(ngModel)]="singleValue2">
    </nouislider>

    <nouislider [config]="rangeConfig" [(ngModel)]="rangeValue1"></nouislider>

    <!-- Full -->

    <nouislider [config]="fullConfig" [(ngModel)]="fullValue1"></nouislider>

    <nouislider [config]="verticalFullConfig" [(ngModel)]="fullValue2"></nouislider>

    <!-- Variations -->

    <nouislider class="noUi-primary" [behaviour]="'tap-drag'" [tooltips]="true" [config]="rangeConfig" [(ngModel)]="rangeValue2"></nouislider>

    <nouislider class="noUi-secondary" [behaviour]="'tap-drag'" [tooltips]="true" [config]="rangeConfig" [(ngModel)]="rangeValue3"></nouislider>

    <nouislider class="noUi-success" [behaviour]="'tap-drag'" [tooltips]="true" [config]="rangeConfig" [(ngModel)]="rangeValue4"></nouislider>

    <nouislider class="noUi-warning" [behaviour]="'tap-drag'" [tooltips]="true" [config]="rangeConfig" [(ngModel)]="rangeValue5"></nouislider>

    <nouislider class="noUi-info" [behaviour]="'tap-drag'" [tooltips]="true" [config]="rangeConfig" [(ngModel)]="rangeValue6"></nouislider>

    <nouislider class="noUi-danger" [behaviour]="'tap-drag'" [tooltips]="true" [config]="rangeConfig" [(ngModel)]="rangeValue7"></nouislider>

    <nouislider class="noUi-dark" [behaviour]="'tap-drag'" [tooltips]="true" [config]="rangeConfig" [(ngModel)]="rangeValue8"></nouislider>
  </div>
</div>

// vue-demo/src/components/forms/Sliders.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">Forms /</span> Sliders
    </h4>

    <b-card header="Default Bootstrap 4 slider" header-tag="h6" class="mb-4">
      <div class="demo-vertical-spacing">
        <b-form-input type="range" v-model="bs4SliderValue" />
        <p>Value: <strong>{{ bs4SliderValue }}</strong></p>

        <b-form-input type="range" v-model="bs4SliderValue" :disabled="true" />
      </div>
    </b-card>

    <b-card header="noUiSlider" header-tag="h6" class="mb-4">
      <div class="demo-vertical-spacing-lg px-4 pt-4 pb-5">
        <nouislider
          ref="slider"
          v-model="singleValue"
          :options="options1"
          :disabled="isDisabled"
          @update="logEvent('update', $event)"
          @slide="logEvent('slide', $event)"
          @set="logEvent('set', $event)"
          @change="logEvent('change', $event)"
          @start="logEvent('start', $event)"
          @end="logEvent('end', $event)" />

        <div style="margin-top: 2rem !important;">
          <pre><strong>Value: </strong>{{ singleValue }}</pre>
          <pre><strong>Last event: </strong>{{ lastEvent.name }}<br><strong>Value: </strong>{{ lastEvent.value }}</pre>

          <b-btn variant="default" @click="toggleDisabled">Toggle disabled</b-btn>
          <b-btn variant="default" @click="toggleConnect">Toggle "connect" option</b-btn>
          <b-btn variant="default" @click="toggleTooltips">Toggle "tooltips" option</b-btn>
          <b-btn variant="default" @click="reset">reset()</b-btn>
        </div>

        <!-- Vertical -->

        <nouislider v-model="singleValue" :options="options2" style="height:200px;margin:0 auto 30px"></nouislider>

        <!-- Range -->

        <nouislider v-model="rangeValue" :options="options3"></nouislider>

        <!-- Full example -->

        <nouislider v-model="fullValue" :options="options4"></nouislider>

        <nouislider v-model="fullValue" :options="options5" style="height:400px;margin:0 auto 30px"></nouislider>

        <!-- Colors -->

        <div class="noUi-primary">
          <nouislider v-model="rangeValue" :options="options6"></nouislider>
        </div>
        <div class="noUi-secondary">
          <nouislider v-model="rangeValue" :options="options6"></nouislider>
        </div>
        <div class="noUi-success">
          <nouislider v-model="rangeValue" :options="options6"></nouislider>
        </div>
        <div class="noUi-info">
          <nouislider v-model="rangeValue" :options="options6"></nouislider>
        </div>
        <div class="noUi-warning">
          <nouislider v-model="rangeValue" :options="options6"></nouislider>
        </div>
        <div class="noUi-danger">
          <nouislider v-model="rangeValue" :options="options6"></nouislider>
        </div>
        <div class="noUi-dark">
          <nouislider v-model="rangeValue" :options="options6"></nouislider>
        </div>
      </div>
    </b-card>

    <b-card header="Vue Slider Component" header-tag="h6" class="mb-4">
      <div class="demo-vertical-spacing-lg">
        <vue-slider v-model="vueSliderSingleValue" :height="2" :dotSize="12" tooltip="focus" :direction="isRTL ? 'rtl' : 'ltr'" :disabled="vueSliderDisabled" />

        <div class="mt-4">
          <pre class="mb-4">{{ vueSliderSingleValue }}</pre>
          <b-btn variant="default" @click="vueSliderDisabled = !vueSliderDisabled">Disabled</b-btn>
        </div>

        <vue-slider
          v-model="vueSliderSingleValue"
          :height="2"
          :dotSize="12"
          :interval="10"
          :marks="(v) => ({ label: `$${v}` })"
          :stepStyle="{width:'6px',height:'6px'}"
          tooltip="always"
          tooltipFormatter="${value}"
          :direction="isRTL ? 'rtl' : 'ltr'"
          :disabled="vueSliderDisabled" />

        <!-- Range -->

        <vue-slider
          v-model="vueSliderRangeValue"
          :data="vueSliderRangeData"
          :height="2"
          :dotSize="12"
          tooltip="always"
          :direction="isRTL ? 'rtl' : 'ltr'"
          :disabled="vueSliderDisabled" />

        <pre style="margin-top: 2rem !important">{{ vueSliderRangeValue }}</pre>

        <!-- Vertical -->

        <div>
          <vue-slider class="d-inline-block mr-5"
            v-model="vueSliderSingleValue"
            :direction="'ttb'"
            :width="2"
            :height="200"
            :dotSize="12"
            tooltip="always"
            :tooltipPlacement="!isRTL ? 'right' : 'left'"
            :disabled="vueSliderDisabled" />

          <vue-slider class="d-inline-block"
            v-model="vueSliderSingleValue"
            :direction="'btt'"
            :width="2"
            :height="200"
            :dotSize="12"
            tooltip="always"
            :tooltipPlacement="!isRTL ? 'right' : 'left'"
            :disabled="vueSliderDisabled" />
        </div>

        <!-- Custom styling -->

        <vue-slider
          v-model="vueSliderRangeValue"
          :data="vueSliderRangeData"
          :height="2"
          :dotSize="12"
          :dotStyle="{ backgroundColor: '#f05b72', boxShadow: 'none' }"
          :tooltipStyle="{ backgroundColor: '#f05b72', borderColor: '#f05b72' }"
          :processStyle="{ backgroundImage: `linear-gradient(to ${!isRTL ? 'right' : 'left'}, #f05b72, #3498db)` }"
          tooltip="always"
          :direction="isRTL ? 'rtl' : 'ltr'"
          :disabled="vueSliderDisabled" />

        <!-- Variants -->

        <vue-slider class="vue-slider-primary" v-model="vueSliderRangeValue" :data="vueSliderRangeData" :height="2" :dotSize="12" tooltip="always" :direction="isRTL ? 'rtl' : 'ltr'" :disabled="vueSliderDisabled" />
        <vue-slider class="vue-slider-secondary" v-model="vueSliderRangeValue" :data="vueSliderRangeData" :height="2" :dotSize="12" tooltip="always" :direction="isRTL ? 'rtl' : 'ltr'" :disabled="vueSliderDisabled" />
        <vue-slider class="vue-slider-success" v-model="vueSliderRangeValue" :data="vueSliderRangeData" :height="2" :dotSize="12" tooltip="always" :direction="isRTL ? 'rtl' : 'ltr'" :disabled="vueSliderDisabled" />
        <vue-slider class="vue-slider-warning" v-model="vueSliderRangeValue" :data="vueSliderRangeData" :height="2" :dotSize="12" tooltip="always" :direction="isRTL ? 'rtl' : 'ltr'" :disabled="vueSliderDisabled" />
        <vue-slider class="vue-slider-info" v-model="vueSliderRangeValue" :data="vueSliderRangeData" :height="2" :dotSize="12" tooltip="always" :direction="isRTL ? 'rtl' : 'ltr'" :disabled="vueSliderDisabled" />
        <vue-slider class="vue-slider-danger" v-model="vueSliderRangeValue" :data="vueSliderRangeData" :height="2" :dotSize="12" tooltip="always" :direction="isRTL ? 'rtl' : 'ltr'" :disabled="vueSliderDisabled" />
        <vue-slider class="vue-slider-dark" v-model="vueSliderRangeValue" :data="vueSliderRangeData" :height="2" :dotSize="12" tooltip="always" :direction="isRTL ? 'rtl' : 'ltr'" :disabled="vueSliderDisabled" />
      </div>
    </b-card>

  </div>
</template>

<style src="@/vendor/libs/vue-slider-component/vue-slider-component.scss" lang="scss"></style>

<script>
import Nouislider from '@/vendor/libs/nouislider/Nouislider'
import vueSlider from 'vue-slider-component'

export default {
  name: 'forms-sliders',
  metaInfo: {
    title: 'Sliders - Forms'
  },
  components: {
    Nouislider,
    vueSlider
  },
  data: () => ({
    //
    // Bootstrap 4 slider
    //

    bs4SliderValue: 35,

    //
    // noUiSlider
    //

    singleValue: ['80.00'],
    rangeValue: ['4000', '8000'],
    fullValue: ['1450', '2050', '2350', '3000'],

    isDisabled: false,
    lastEvent: { name: '', value: '' },

    // Default
    options1: {
      step: 1,
      connect: [false, false],
      range: {
        min: 0,
        max: 100
      }
    },

    // Vertical
    options2: {
      orientation: 'vertical',
      direction: 'rtl',
      step: 1,
      range: {
        min: 0,
        max: 100
      }
    },

    // Range
    options3: {
      step: 1000,
      connect: true,
      range: {
        min: [2000],
        max: [10000]
      }
    },

    // Full
    options4: {
      connect: true,
      behaviour: 'tap-drag',
      step: 150,
      tooltips: true,
      range: {
        min: 1000,
        max: 3750
      },
      pips: {
        mode: 'steps',
        stepped: true,
        density: 4
      }
    },

    // Vertical
    options5: {
      connect: true,
      behaviour: 'tap-drag',
      step: 150,
      tooltips: true,
      direction: 'rtl',
      orientation: 'vertical',
      range: {
        min: 1000,
        max: 3750
      },
      pips: {
        mode: 'steps',
        stepped: true,
        density: 4
      }
    },

    // Colors
    options6: {
      connect: true,
      behaviour: 'tap-drag',
      step: 1000,
      tooltips: true,
      range: {
        min: [2000],
        max: [10000]
      },
      pips: {
        mode: 'steps',
        stepped: true,
        density: 4
      }
    },

    //
    // Vue Slider Component
    //

    vueSliderDisabled: false,
    vueSliderSingleValue: 75,
    vueSliderRangeValue: ['10-03', '10-11'],
    vueSliderRangeData: [
      '10-01', '10-02', '10-03', '10-04', '10-05', '10-06', '10-07', '10-08',
      '10-09', '10-10', '10-11', '10-12', '10-13', '10-14', '10-15', '10-16',
      '10-17', '10-18', '10-19', '10-20'
    ]
  }),
  methods: {
    //
    // noUiSlider
    //

    toggleDisabled () {
      this.isDisabled = !this.isDisabled
    },
    toggleConnect () {
      this.options1 = Object.assign({}, this.options1, { connect: [this.options1.connect[0] === false, false] })
    },
    toggleTooltips () {
      this.options1 = Object.assign({}, this.options1, { tooltips: !this.options1.tooltips })
    },
    reset () {
      this.$refs.slider.$el.noUiSlider.reset()
    },
    logEvent (name, $event) {
      this.lastEvent = { name, value: $event[0] }
    }
  },
  mounted () {
    //
    // noUiSlider
    //

    // Handle RTL direction
    if (this.isRTL) {
      this.options1 = Object.assign({}, this.options1, { direction: 'rtl' })
      this.options3 = Object.assign({}, this.options3, { direction: 'rtl' })
      this.options4 = Object.assign({}, this.options4, { direction: 'rtl' })
      this.options6 = Object.assign({}, this.options6, { direction: 'rtl' })
    }
  }
}
</script>
