// vue-demo/src/cui-components/CuiCustomRangeInput.vue
<template>
  <div class="ui-block">
    <h3 class="ui-block-heading">Custom range input</h3>

    <h4 class="ui-block-heading">Example</h4>

    <div class="cui-example">
      <b-form-input type="range" v-model="bs4SliderValue" />
      <p>Value: <strong>{{ bs4SliderValue }}</strong></p>
    </div>

    <h4 class="ui-block-heading">Disabled</h4>

    <div class="cui-example">
      <b-form-input type="range" v-model="bs4SliderValue" :disabled="true" />
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    bs4SliderValue: 35
  })
}
</script>

// angular-demo/src/app/+complete-ui/cui-custom-range-input/cui-custom-range-input.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cui-custom-range-input', // tslint:disable-line
  templateUrl: './cui-custom-range-input.component.html'
})
export class CuiCustomRangeInputComponent {
  bs4SliderValue = 35;
}

<div class="ui-block">
  <h3 class="ui-block-heading">Custom range input</h3>

  <h4 class="ui-block-heading">Example</h4>

  <div class="cui-example">
    <input type="range" [(ngModel)]="bs4SliderValue" class="custom-range">
    <p>Value: <strong>{{ bs4SliderValue }}</strong></p>
  </div>

  <h4 class="ui-block-heading">Disabled</h4>

  <div class="cui-example">
    <input type="range" [(ngModel)]="bs4SliderValue" class="custom-range" disabled>
  </div>
</div>
