// angular-demo/src/app/+ui/spinners/spinners.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'ui-spinners', // tslint:disable-line
  templateUrl: './spinners.component.html'
})
export class SpinnersComponent {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Spinners - UI elements';
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">UI elements /</span> Spinners
</h4>

<div class="card mb-4">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Border</div>

    <div class="demo-inline-spacing">
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border text-primary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border text-secondary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border text-success" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border text-danger" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border text-warning" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border text-info" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border text-light" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border text-dark" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Growing</div>

    <div class="demo-inline-spacing">
      <div class="spinner-grow" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow text-primary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow text-secondary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow text-success" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow text-danger" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow text-warning" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow text-info" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow text-light" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow text-dark" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Small</div>

    <div class="demo-inline-spacing">
      <div class="spinner-border spinner-border-sm" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border spinner-border-sm text-primary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border spinner-border-sm text-secondary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border spinner-border-sm text-success" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border spinner-border-sm text-danger" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border spinner-border-sm text-warning" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border spinner-border-sm text-info" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border spinner-border-sm text-light" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-border spinner-border-sm text-dark" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>

    <div class="demo-inline-spacing">
      <div class="spinner-grow spinner-grow-sm" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow spinner-grow-sm text-primary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow spinner-grow-sm text-secondary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow spinner-grow-sm text-success" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow spinner-grow-sm text-danger" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow spinner-grow-sm text-warning" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow spinner-grow-sm text-info" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow spinner-grow-sm text-light" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <div class="spinner-grow spinner-grow-sm text-dark" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-body">
    <div class="text-light small font-weight-semibold mb-3">Within buttons</div>

    <div class="demo-inline-spacing">
      <!-- Extra small -->
      <button class="btn btn-xs btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-xs btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        Loading...
      </button>

      <!-- Small -->
      <button class="btn btn-sm btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-sm btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        Loading...
      </button>

      <!-- Default -->
      <button class="btn btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        Loading...
      </button>

      <!-- Large -->
      <button class="btn btn-lg btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-lg btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        Loading...
      </button>

      <!-- Extra large -->
      <button class="btn btn-xl btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-xl btn-primary" type="button" disabled>
        <span class="spinner-border" role="status" aria-hidden="true"></span>
        Loading...
      </button>
    </div>

    <div class="demo-inline-spacing">
      <!-- Extra small -->
      <button class="btn btn-xs btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-xs btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        Loading...
      </button>

      <!-- Small -->
      <button class="btn btn-sm btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-sm btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        Loading...
      </button>

      <!-- Default -->
      <button class="btn btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        Loading...
      </button>

      <!-- Large -->
      <button class="btn btn-lg btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-lg btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        Loading...
      </button>

      <!-- Extra large -->
      <button class="btn btn-xl btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        <span class="sr-only">Loading...</span>
      </button>
      <button class="btn btn-xl btn-primary" type="button" disabled>
        <span class="spinner-grow" role="status" aria-hidden="true"></span>
        Loading...
      </button>
    </div>
  </div>
</div>

// vue-demo/src/components/ui/Spinners.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">UI elements /</span> Spinners
    </h4>

    <b-card no-body>
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Border</div>

        <div class="demo-inline-spacing">
          <b-spinner label="Spinning" />
          <b-spinner label="Spinning" variant="primary" />
          <b-spinner label="Spinning" variant="secondary" />
          <b-spinner label="Spinning" variant="success" />
          <b-spinner label="Spinning" variant="danger" />
          <b-spinner label="Spinning" variant="warning" />
          <b-spinner label="Spinning" variant="info" />
          <b-spinner label="Spinning" variant="light" />
          <b-spinner label="Spinning" variant="dark" />
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Growing</div>

        <div class="demo-inline-spacing">
          <b-spinner label="Spinning" type="grow" />
          <b-spinner label="Spinning" type="grow" variant="primary" />
          <b-spinner label="Spinning" type="grow" variant="secondary" />
          <b-spinner label="Spinning" type="grow" variant="success" />
          <b-spinner label="Spinning" type="grow" variant="danger" />
          <b-spinner label="Spinning" type="grow" variant="warning" />
          <b-spinner label="Spinning" type="grow" variant="info" />
          <b-spinner label="Spinning" type="grow" variant="light" />
          <b-spinner label="Spinning" type="grow" variant="dark" />
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Small</div>

        <div class="demo-inline-spacing">
          <b-spinner label="Spinning" small />
          <b-spinner label="Spinning" small variant="primary" />
          <b-spinner label="Spinning" small variant="secondary" />
          <b-spinner label="Spinning" small variant="success" />
          <b-spinner label="Spinning" small variant="danger" />
          <b-spinner label="Spinning" small variant="warning" />
          <b-spinner label="Spinning" small variant="info" />
          <b-spinner label="Spinning" small variant="light" />
          <b-spinner label="Spinning" small variant="dark" />
        </div>

        <div class="demo-inline-spacing">
          <b-spinner label="Spinning" type="grow" small />
          <b-spinner label="Spinning" type="grow" small variant="primary" />
          <b-spinner label="Spinning" type="grow" small variant="secondary" />
          <b-spinner label="Spinning" type="grow" small variant="success" />
          <b-spinner label="Spinning" type="grow" small variant="danger" />
          <b-spinner label="Spinning" type="grow" small variant="warning" />
          <b-spinner label="Spinning" type="grow" small variant="info" />
          <b-spinner label="Spinning" type="grow" small variant="light" />
        </div>
      </b-card-body>
      <hr class="m-0">
      <b-card-body>
        <div class="text-light small font-weight-semibold mb-3">Within buttons</div>

        <div class="demo-inline-spacing">
          <!-- Extra small -->
          <b-button variant="primary" class="btn-xs" disabled>
            <b-spinner />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" class="btn-xs" disabled>
            <b-spinner />
            Loading...
          </b-button>

          <!-- Small -->
          <b-button variant="primary" size="sm" disabled>
            <b-spinner />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" size="sm" disabled>
            <b-spinner />
            Loading...
          </b-button>

          <!-- Default -->
          <b-button variant="primary" disabled>
            <b-spinner />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" disabled>
            <b-spinner />
            Loading...
          </b-button>

          <!-- Large -->
          <b-button variant="primary" size="lg" disabled>
            <b-spinner />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" size="lg" disabled>
            <b-spinner />
            Loading...
          </b-button>

          <!-- Extra large -->
          <b-button variant="primary" class="btn-xl" disabled>
            <b-spinner />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" class="btn-xl" disabled>
            <b-spinner />
            Loading...
          </b-button>
        </div>

        <div class="demo-inline-spacing">
          <!-- Extra small -->
          <b-button variant="primary" class="btn-xs" disabled>
            <b-spinner type="grow" />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" class="btn-xs" disabled>
            <b-spinner type="grow" />
            Loading...
          </b-button>

          <!-- Small -->
          <b-button variant="primary" size="sm" disabled>
            <b-spinner type="grow" />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" size="sm" disabled>
            <b-spinner type="grow" />
            Loading...
          </b-button>

          <!-- Default -->
          <b-button variant="primary" disabled>
            <b-spinner type="grow" />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" disabled>
            <b-spinner type="grow" />
            Loading...
          </b-button>

          <!-- Large -->
          <b-button variant="primary" size="lg" disabled>
            <b-spinner type="grow" />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" size="lg" disabled>
            <b-spinner type="grow" />
            Loading...
          </b-button>

          <!-- Extra large -->
          <b-button variant="primary" class="btn-xl" disabled>
            <b-spinner type="grow" />
            <span class="sr-only">Loading...</span>
          </b-button>
          <b-button variant="primary" class="btn-xl" disabled>
            <b-spinner type="grow" />
            Loading...
          </b-button>
        </div>
      </b-card-body>
    </b-card>

  </div>
</template>

<script>
export default {
  name: 'ui-spinners',
  metaInfo: {
    title: 'Spinners - UI elements'
  }
}
</script>
