// angular-demo/src/app/+miscellaneous/brand-colors/brand-colors.component.ts
import { Component } from '@angular/core';
import { AppService } from '../../app.service';

@Component({
  selector: 'miscellaneous-brand-colors', // tslint:disable-line
  templateUrl: './brand-colors.component.html'
})
export class BrandColorsComponent {
  constructor(private appService: AppService) {
    this.appService.pageTitle = 'Brand colors - Miscellaneous';
  }
}

<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Miscellaneous /</span> Brand colors
</h4>

<div class="card">
  <div class="card-body text-center">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-twitter text-white p-4">.bg-twitter</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-twitter">.text-twitter</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-twitter">.btn-twitter</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-twitter">.btn-outline-twitter</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-google text-white p-4">.bg-google</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-google">.text-google</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-google">.btn-google</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-google">.btn-outline-google</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-facebook text-white p-4">.bg-facebook</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-facebook">.text-facebook</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-facebook">.btn-facebook</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-facebook">.btn-outline-facebook</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-pinterest text-white p-4">.bg-pinterest</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-pinterest">.text-pinterest</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-pinterest">.btn-pinterest</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-pinterest">.btn-outline-pinterest</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-instagram text-white p-4">.bg-instagram</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-instagram">.text-instagram</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-instagram">.btn-instagram</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-instagram">.btn-outline-instagram</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-flickr text-white p-4">.bg-flickr</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-flickr">.text-flickr</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-flickr">.btn-flickr</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-flickr">.btn-outline-flickr</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-linkedin text-white p-4">.bg-linkedin</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-linkedin">.text-linkedin</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-linkedin">.btn-linkedin</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-linkedin">.btn-outline-linkedin</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-periscope text-white p-4">.bg-periscope</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-periscope">.text-periscope</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-periscope">.btn-periscope</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-periscope">.btn-outline-periscope</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-tumblr text-white p-4">.bg-tumblr</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-tumblr">.text-tumblr</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-tumblr">.btn-tumblr</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-tumblr">.btn-outline-tumblr</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-vimeo text-white p-4">.bg-vimeo</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-vimeo">.text-vimeo</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-vimeo">.btn-vimeo</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-vimeo">.btn-outline-vimeo</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-youtube text-white p-4">.bg-youtube</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-youtube">.text-youtube</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-youtube">.btn-youtube</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-youtube">.btn-outline-youtube</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-windows text-white p-4">.bg-windows</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-windows">.text-windows</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-windows">.btn-windows</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-windows">.btn-outline-windows</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-macos text-white p-4">.bg-macos</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-macos">.text-macos</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-macos">.btn-macos</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-macos">.btn-outline-macos</button>
      </div>
    </div>

    <hr class="mx-n4 my-4">

    <div class="row align-items-center">
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <div class="bg-linux text-white p-4">.bg-linux</div>
      </div>
      <div class="col-6 col-md-3 mb-4 mb-md-0">
        <a href="javascript:void(0)" class="text-linux">.text-linux</a>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-linux">.btn-linux</button>
      </div>
      <div class="col-6 col-md-3">
        <button type="button" class="btn btn-outline-linux">.btn-outline-linux</button>
      </div>
    </div>

  </div>
</div>

// vue-demo/src/components/miscellaneous/BrandColors.vue
<template>
  <div>
    <h4 class="font-weight-bold py-3 mb-4">
      <span class="text-muted font-weight-light">Miscellaneous /</span> Brand colors
    </h4>

    <b-card body-class="text-center">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-twitter text-white p-4">.bg-twitter</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-twitter">.text-twitter</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-twitter">.btn-twitter</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-twitter">.btn-outline-twitter</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-google text-white p-4">.bg-google</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-google">.text-google</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-google">.btn-google</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-google">.btn-outline-google</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-facebook text-white p-4">.bg-facebook</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-facebook">.text-facebook</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-facebook">.btn-facebook</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-facebook">.btn-outline-facebook</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-pinterest text-white p-4">.bg-pinterest</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-pinterest">.text-pinterest</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-pinterest">.btn-pinterest</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-pinterest">.btn-outline-pinterest</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-instagram text-white p-4">.bg-instagram</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-instagram">.text-instagram</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-instagram">.btn-instagram</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-instagram">.btn-outline-instagram</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-flickr text-white p-4">.bg-flickr</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-flickr">.text-flickr</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-flickr">.btn-flickr</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-flickr">.btn-outline-flickr</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-linkedin text-white p-4">.bg-linkedin</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-linkedin">.text-linkedin</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-linkedin">.btn-linkedin</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-linkedin">.btn-outline-linkedin</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-periscope text-white p-4">.bg-periscope</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-periscope">.text-periscope</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-periscope">.btn-periscope</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-periscope">.btn-outline-periscope</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-tumblr text-white p-4">.bg-tumblr</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-tumblr">.text-tumblr</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-tumblr">.btn-tumblr</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-tumblr">.btn-outline-tumblr</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-vimeo text-white p-4">.bg-vimeo</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-vimeo">.text-vimeo</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-vimeo">.btn-vimeo</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-vimeo">.btn-outline-vimeo</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-youtube text-white p-4">.bg-youtube</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-youtube">.text-youtube</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-youtube">.btn-youtube</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-youtube">.btn-outline-youtube</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-windows text-white p-4">.bg-windows</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-windows">.text-windows</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-windows">.btn-windows</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-windows">.btn-outline-windows</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-macos text-white p-4">.bg-macos</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-macos">.text-macos</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-macos">.btn-macos</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-macos">.btn-outline-macos</button>
        </div>
      </div>

      <hr class="mx-n4 my-4">

      <div class="row align-items-center">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <div class="bg-linux text-white p-4">.bg-linux</div>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <a href="javascript:void(0)" class="text-linux">.text-linux</a>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-linux">.btn-linux</button>
        </div>
        <div class="col-6 col-md-3">
          <button type="button" class="btn btn-outline-linux">.btn-outline-linux</button>
        </div>
      </div>

    </b-card>
  </div>
</template>

<script>
export default {
  name: 'miscellaneous-brand-colors',
  metaInfo: {
    title: 'Brand colors - Miscellaneous'
  }
}
</script>
